org: frossard
app: staircase-assessment
service: staircase-assessment

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  environment:
    bucketName: ${self:custom.blobsBucketName}
    tableName: ${self:custom.blobsTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'
    - Effect: "Allow"
      Action:
       - "s3:*"
      Resource: ${self:custom.arnPrefix}${self:custom.blobsBucketName}${self:custom.arnSufix}
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"

custom:
  blobsTableName: blobs
  blobsBucketName: daniel-frosard-staircase-reko-blobs-bucket
  arnPrefix: 'arn:aws:s3:::'
  arnSufix: '/*'

functions:
  getBlobInfo:
    handler: lambdas/getBlobInfo.handler
    events:
      - http:
          path: blobs/
          method: get
  createBlob:
    handler: lambdas/createBlob.handler
    events:
      - http:
          path: blobs/
          method: post
  processBlob:
    handler: lambdas/processBlob.handler
    events:
      - s3:
          bucket: ${self:custom.blobsBucketName}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .jpg
      - s3:
          bucket: ${self:custom.blobsBucketName}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
      - s3:
          bucket: ${self:custom.blobsBucketName}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .jpeg
      - s3:
          bucket: ${self:custom.blobsBucketName}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .JPG
  makeCallback:
    handler: lambdas/makeCallback.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [blobsTable, StreamArn]


resources:
  Resources:
    blobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.blobsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
