org: frossard
app: staircase-assessment
service: staircase-assessment

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

custom:
  tableName: blobs

functions:
  createBlob:
    handler: handler.hello
    events:
      - http:
          path: blobs/
          method: post

resources:
  Resources:
    blobsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: reko-blobs-bucket
    blobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
